[pytest]
testpaths = unitTest
python_files = test_*.py
python_functions = test_*
addopts = -ra
markers =
    auth: authentication tests
    users: user route tests
    profiles: profile route tests
    matches: match route tests